### PR TITLE
Cash Register

### PR DESCRIPTION
**Pull request by zainabbehzad**
Cash Register Project:
* First of all I created the repo according the project requirements.
* Followed the Gitflow.
* Setup the Linters configuration for my project.
* Created HTML, CSS, and JavaScript files to create structure of my project by HTML codes, added design to my project by CSS codes, and added functionality to my project by JavaScript codes.
* Made responsive my project.
* Added README.md file to my project.
* When I finished my project test the codes in FreeCodeCamp and passes all it's requirements.

Screenshot (56)

### CODE REVIEW

**Comment by zainabbehzad** [comment]
@Marwa-Sadat
Hi Marwa jan
please review my project

**Comment by Marwa-Sadat** [comment]
Approval: @Marwa-Sadat approved this pull request.


Hi @Zainab-Behzad 🙋‍♀,

Wow, this is fantastic! 💯 You’ve done an amazing job with the Cash Register project. 🥳 Your implementation meets all the project requirements flawlessly. Congratulations!!! 🎉

Project Sharing:

	•	[REQUIRED] Share your project on this GROUP with a simple Proud Moment text and a screenshot of your project. Add your project link at the end as a GitHub source code reference and post.
	•	Share your project on your LinkedIn account with a Proud Moment text and a screenshot.

Project Highlights:

	•	🎉 Great design implemented
	•	✔ Created a professional repo (You created a repository with your project name)
	•	✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
	•	✔ Commit messages are meaningful
	•	✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
	•	✔ No linter errors (All linters checks have been passed 🟢)
	•	✔ You have followed the Cash Register project task and committed using the command line
	•	✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
	•	✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
	•	✔ Your code is clean
	•	✔ Your repo has a professional README.md file
	•	✔ Your design is responsive

Status: Approved ✅

There’s nothing left to say other than to merge your branch. 🎉🎯✅👍😊🥳

Cheers 🥂 and happy coding!!! Feel free to tag me @Marwa-Sadat if you have any questions.

Make sure to replace placeholders with actual links and details when sharing on platforms.

**Comment by Marwa-Sadat** [comment]
Approval: @Marwa-Sadat approved this pull request.

Hi @Zainab-Behzad 🙋‍♀,

Wow, this is fantastic! 💯 You’ve done an amazing job with the Cash Register project. 🥳 Your implementation meets all the project requirements flawlessly. Congratulations!!! 🎉

Project Sharing:

	•	[REQUIRED] Share your project on this GROUP with a simple Proud Moment text and a screenshot of your project. Add your project link at the end as a GitHub source code reference and post.
	•	Share your project on your LinkedIn account with a Proud Moment text and a screenshot.

Project Highlights:

	•	🎉 Great design implemented
	•	✔ Created a professional repo (You created a repository with your project name)
	•	✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
	•	✔ Commit messages are meaningful
	•	✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
	•	✔ No linter errors (All linters checks have been passed 🟢)
	•	✔ You have followed the Cash Register project task and committed using the command line
	•	✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
	•	✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
	•	✔ Your code is clean
	•	✔ Your repo has a professional README.md file
	•	✔ Your design is responsive

Status: Approved ✅

There’s nothing left to say other than to merge your branch. 🎉🎯✅👍😊🥳

Cheers 🥂 and happy coding!!! Feel free to tag me @Marwa-Sadat if you have any questions.

Make sure to replace placeholders with actual links and details when sharing on platforms.

**Comment by Marwa-Sadat** [comment]
Approval: @Marwa-Sadat approved this pull request.

Hi @Zainab-Behzad 🙋‍♀,

Wow, this is fantastic! 💯 You’ve done an amazing job with the Cash Register project. 🥳 Your implementation meets all the project requirements flawlessly. Congratulations!!! 🎉

Project Sharing:

	•	[REQUIRED] Share your project on this GROUP with a simple Proud Moment text and a screenshot of your project. Add your project link at the end as a GitHub source code reference and post.
	•	Share your project on your LinkedIn account with a Proud Moment text and a screenshot.

Project Highlights:

	•	🎉 Great design implemented
	•	✔ Created a professional repo (You created a repository with your project name)
	•	✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
	•	✔ Commit messages are meaningful
	•	✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
	•	✔ No linter errors (All linters checks have been passed 🟢)
	•	✔ You have followed the Cash Register project task and committed using the command line
	•	✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
	•	✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
	•	✔ Your code is clean
	•	✔ Your repo has a professional README.md file
	•	✔ Your design is responsive

Status: Approved ✅

There’s nothing left to say other than to merge your branch. 🎉🎯✅👍😊🥳

Cheers 🥂 and happy coding!!! Feel free to tag me @Marwa-Sadat if you have any questions.

Make sure to replace placeholders with actual links and details when sharing on platforms.

**Review by Marwa-Sadat — APPROVED** [review]
OK

**Comment by Marwa-Sadat** [comment]
Approval: @Marwa-Sadat approved this pull request.
Hi @Zainab-Behzad 🙋‍♀,
Great work on the Cash Register project! Your implementation meets all the requirements perfectly. Congratulations on a job well done! 🎉
Project Sharing:
	•	[REQUIRED] Share your project on this GROUP with a simple Proud Moment text and a screenshot of your project. Add your project link as a GitHub source code reference at the end of your post.
	•	Share your project on your LinkedIn account with a Proud Moment text and a screenshot.
Project Highlights:
	•	🎉 Great design implemented
	•	✔ Professional repo setup
	•	✔ Correct use of Gitflow
	•	✔ Meaningful commit messages
	•	✔ Correct setup of linters
	•	✔ No linter errors 🟢
	•	✔ Followed project tasks and used CLI for commits
	•	✔ Created and submitted pull request for review
	•	✔ Good PR description
	•	✔ Clean code
	•	✔ Professional README.md file
	•	✔ Responsive design
Status: Approved ✅
Feel free to merge your branch. 🎉🎯✅👍😊🥳
Cheers 🥂 and happy coding!!! If you have any questions, feel free to tag me @Marwa-Sadat.

**Comment by zainabbehzad** [comment]
@ahzamir
hello sir!
hope you doing well
please review my project

**Comment by ahzamir** [comment]
@zainabbehzad 

- Well done you have done a great job by implementing the requirements as your codes do not pass checks on freecodecamp for me so I want you to share the screenshot of freecodecamp passing all checks for you so I can approve your project.

**Comment by zainabbehzad** [comment]
@ahzamir 
Hello Sir!
Please review my project.
I have added a new screenshot of FreeCodeCamp.

**Review by ahzamir — APPROVED** [review]
### Hi @zainabbehzad 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by zainabbehzad** [comment]
@ahzamir 
Thanks Sir 🙏

**Pull request merged**
